testinfo:
    - id: test_settings_001
      title: 设置-基本设置
      info: 设置-基本设置相关测试
testcase:
    - element_info: $tab_personal
      find_type: $id
      operate_type: click
      info: 点击'我'按钮

    - element_info: $settings_btn
      find_type: $id
      operate_type: click
      info: 点击'设置'按钮

    - element_info: $receive_notice
      find_type: $text
      operate_type: click
      info: 点击'接收通知推送'

    - element_info: $receive_checkbox
      find_type: $class_name
      operate_type: click
      info: 任意关闭一个通知推送设置

    - element_info: $comm_back
      find_type: $id
      operate_type: click
      info: 返回设置页

    - element_info: $lang
      find_type: $text
      operate_type: click
      info: 点击'已选择语言'

    - element_info: $lang_cho_English
      find_type: $text
      operate_type: click
      info: 选择'English'

    - element_info: $lang_English
      find_type: $text
      operate_type: click
      info: 选择'已选择语言'

    - element_info: $lang_swipe
      find_type: $text
      operate_type: swipe_up
      info: 上滑动

    - element_info: $lang_swipe_melayu
      find_type: $text
      operate_type: swipe_up
      info: 上滑动

    - element_info: $lang_cho_chinese
      find_type: $text
      operate_type: click
      info: 选择'简体中文'
check:
    - element_info: $privacy_set
      find_type: $text
      check: default_check
      info: 验证返回设置页